<?php

// START - ENG ========================================================

namespace language\en\applications\iam\user\actions\exception {
    const admin = 'Generated by your administrator!';
}

namespace language\en\applications\iam\user\actions\email {
    const title = 'Change password successfull!';
    const subject = 'Modify Password!';
    const hello = 'Goodmorning';
    const passwordmessage = 'your password is:';
    const message = 'Your password for signing in to Energia Europa was recently changed. If you made this change, then we\'re all set.';
    const submessage = 'If you didn\'t ask to change it, feel free to contact us. We\'re here to help.';
}

// END - ENG ==========================================================

// START - ITA ========================================================

namespace language\it\applications\iam\user\actions\exception {
    const admin = 'Generato dal tuo amministratore!';
}

namespace language\it\applications\iam\user\actions\email {
    const title = 'Password cambiata correttamente!';
    const subject = 'Password Modificata!';
    const hello = 'Buongiorno';
    const passwordmessage = 'la tua passwor è:';
    const message = 'La tua password per accedere ad Energia Europa è stata modificata recentemente.';
    const submessage = 'Se non sei stato tu a richiedere di cambiarla, sentiti libero di contattarci. Siamo qui per aiutarti.';
}

// END - ITA ==========================================================
